[env]
RUST_LOG = "warn"
WGPU_BACKEND = "vulkan"
RUST_BACKTRACE = 1

[tasks.run]
command = "cargo"
args = ["run"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.check]
command = "cargo"
args = ["check"]

[tasks.web-build]
script_runner = "@shell"
script = '''
wasm-pack build --target web
mkdir -p dist/
rm -rf dist/
mkdir dist/
mkdir dist/pkg/
mv pkg/* dist/pkg/
rmdir pkg
cp public/index.html dist/
'''

[tasks.http-server]
command = "python"
args = ["-m", "http.server", "8800", "-d", "./dist"]

[tasks.web]
description = "Build for web and start an HTTP server"
dependencies = ["web-build", "http-server"]
