name: CI
on: [push, pull_request]
env:
  CLICOLOR_FORCE: 1
  CARGO_TERM_COLOR: always
jobs:
  ci:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install cargo-make
      run: cargo install --debug cargo-make
    - name: Install wasm-pack
      run: cargo install --debug wasm-pack
    - name: Build native
      run: cargo make build
    - name: Build web
      run: cargo make web
